name: Dependency Updates

on:
  schedule:
    - cron: '0 0 * * 1' # Run every Monday at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  check-for-updates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or your preferred Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Check for dependency updates
        id: ncu
        run: npx npm-check-updates --jsonUpgraded # Output only upgraded dependencies in JSON format

      - name: Create Pull Request if updates found
        if: steps.ncu.outputs.stdout != '{}' # Check if ncu found any updates
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: Update dependencies"
          title: "chore: Dependency Updates"
          body: "This PR updates project dependencies to their latest versions."
          branch: "dependency-updates"
          delete-branch: true
